general: &general
  cors:                 <%= ENV["CORS"] %>
  port:                 <%= ENV["PORT"] %>
  localhost:            <%= ENV["LOCALHOST"] %>
  domain_name:          <%= ENV["DOMAIN_NAME"] %>
  domain_name_port:     <%= ENV["DOMAIN_NAME_PORT"] %>
  secret_key_base:      <%= ENV["SECRET_KEY_BASE"] %>
  rack_cors_origins:    <%= ENV["RACK_CORS_ORIGINS"] %>

redis: &redis
  redis_url:            <%= ENV["REDIS_URL"] %>
  redis_data:           <%= ENV["REDIS_DATA"] %>
  redis_cache:          <%= ENV["REDIS_CACHE"] %>
  redis_namespace:      <%= ENV["REDIS_NAMESPACE"] %>

development:
  <<: *general
  <<: *redis

test:
  <<: *general
  <<: *redis

production:
  <<: *general
  <<: *redis
