#!/bin/sh

COLS="$(tput cols)"
COLORS=$(($COLS/5))
i=0

while [ $i -le $(expr $COLS - 1) ]
do
		if [ $i -le $COLORS ]; then
			echo -n '\033[31m█\033[0m'

		elif [ $i -gt $COLORS ] && [ $i -le $(($COLORS*2)) ]; then

			echo -n '\033[33m█\033[0m'

		elif [ $i -gt $(($COLORS*2)) ] && [ $i -le $(($COLORS*3)) ]; then

			echo -n '\033[93m█\033[0m'

		elif [ $i -gt $(($COLORS*3)) ] && [ $i -le $(($COLORS*4)) ]; then

			echo -n '\033[92m█\033[0m'

		else
			echo -n '\033[32m█\033[0m'
		fi

		sleep 0.01
		i=`expr $i + 1`
done
