rails_version = ENV["RAILS_VERSION"] || "default"

case rails_version
when "default"
  "~> 5.1"
else
  "~> #{rails_version}"
end

version = ENV["RAILS_VERSION"] || '5.1'
eval_gemfile File.expand_path("../gemfiles/#{version}.gemfile", __FILE__)
