version = ENV["VERSION"] || "default"

case version
when "default"
  "~> 5.1"
else
  "~> #{version}"
end

version = ENV["VERSION"] || '5.1'
eval_gemfile File.expand_path("../gemfiles/#{version}.gemfile", __FILE__)
