Date::DATE_FORMATS[:default] = "%m/%d/%Y"
Date::DATE_FORMATS[:printed] = "%a, %d %B %Y"
Date::DATE_FORMATS[:medium]  = "%b %-d, %Y"
Date::DATE_FORMATS[:short]   = "%Y-%m-%d"
Date::DATE_FORMATS[:long]    = "%B %e, %Y"

Time::DATE_FORMATS[:default] = "%m/%d/%Y"
Time::DATE_FORMATS[:medium]  = "%b %-d, %Y %-I:%M%P"
Time::DATE_FORMATS[:printed] = "%a, %d %B %Y"
Time::DATE_FORMATS[:short]   = "%d %b %Y"
Time::DATE_FORMATS[:long]    = "%B %d, %Y %H:%M:%S"
